export const navbar = [
  {
    id: 1,
    title: "Buy",
    path: "/buy",
    element: "",
    icon: "",
    child: [],
  },
  {
    id: 2,
    title: "Sell",
    path: "/sell",
    element: "",
    icon: "",
    child: [],
  },
  { id: 3, title: "Rent", path: "/rent", element: "", icon: "", child: [] },
  {
    id: 4,
    title: "My Profile",
    path: "/myprofile",
    element: "",
    icon: "",
    child: [],
  },
  {
    id: 5,
    title: "My home",
    path: "/my home",
    element: "",
    icon: "",
    child: [],
  },
  {
    id: 6,
    title: "Register",
    path: "/register",
    element: "",
    icon: "",
    child: [],
  },
];
